### ISSUE TITLE
Stale dependencies

### ISSUE THREAD

**Issue by jeromecovington** [CondeNast/copilot-util#13]
In our app, which depends on bluebird@3.5.0 (latest version as of this writing). But this repo depends on bluebird@3.3.4, leading to what seems to be unnecessary dependency bloat. Is there any blocker to bumping that version and republishing here?

I also noticed that debug@3.0.1 and immutable@3.8.1 (both most recent versions at the time of this writing) are out of date, so it might make sense to bump those as well.

**Comment by paulfryzel** [comment]
Fixed by: https://github.com/CondeNast/copilot-util/commit/b30c7a214f2c6272cc16caa5685d147903c60e2d
