### ISSUE TITLE
Add browser-compatible distributable

### ISSUE THREAD

**Issue by paulfryzel** [CondeNast/copilot-util#3]
Via browserify (or equivalent) create `/dist/copilot-util.js` and `/dist/copilot-util.min.js`.

It may also be helpful to add a build script/task to automatically create these for each release.

**Comment by pgoldrbx** [comment]
We won't be doing this anymore. Clients should use the modern [WHATWG fetch API](https://fetch.spec.whatwg.org/) and polyfill for older browsers where necessary.
