### ISSUE TITLE
Add debug statements for HTTP Request

### ISSUE THREAD

**Issue by guyellis** [CondeNast/copilot-util#4]
I think that it might be helpful to have the https://www.npmjs.com/package/debug module print this out and initialize it at the top of the HTTP request module with:

```
var debug = require('debug')('copilot-util:http-request');
```

This would allow an env to be set: `DEBUG=copilot-util:http-request` to show network requests to Copilot to help debug or understand how data is being fetched.

I just made those changes in a branch and was going to do a PR to discuss this but I don't have write access to copilot-util. Is it acceptable to fork this repo and do a PR from there?

cc/ @paulfryzel @pgoldrbx

**Comment by paulfryzel** [comment]
@guyellis To note, this is a public/OSS library [on npm](https://www.npmjs.com/package/copilot-util). Currently I'm the sole maintainer. You should fork this repo and submit a PR.
