### ISSUE TITLE
Add FQDNs to errors

### ISSUE THREAD

**Issue by giles-v** [CondeNast/copilot-util#9]
This is a bit related to https://github.com/CondeNast/copilot-util/issues/6, I guess, but I want to be more concrete: we're analyzing timeouts to CI services in our logs right now, and the lack of hostnames in the error logs means we need to distinguish services in those logs based on the _query path_, e.g. filtering 4D logs via `/user?xid` rather than by `4d.condenastdigital.com`. This is not optimal.

I'm thinking of a patch along these lines:

```
diff --git a/lib/http/request/_timeout_listener.js b/lib/http/request/_timeout_listener.js
index d96e8de..5a7698a 100644
--- a/lib/http/request/_timeout_listener.js
+++ b/lib/http/request/_timeout_listener.js
@@ -6,7 +6,7 @@ module.exports = function onTimeout(context, req, options) {
   return function rejectWithTimeoutError() {
     req.abort();
     var te = new error.TimeoutError(options.timeout);
-    te.url = options.path;
+    te.url = url.format(options);
     return context.reject(te);
   };
 };
```

Thoughts welcome. Since this is a low level lib, it seems appropriate to discuss before submitting a PR.

CC @brokentone @paulfryzel

**Comment by pgoldrbx** [comment]
I've considered this a number of times in the past but haven't taken any action. I'd strongly support this change.

**Comment by pgoldrbx** [comment]
This was generally addressed by https://github.com/CondeNast/copilot-util/pull/10
